version: 1
deploy:
  tasks:
    - echo "Starting deployment process..."
    - echo "Installing Node.js dependencies..."
    - npm install
    - echo "Building the Next.js application..."
    - npm run build
    - echo "Deployment tasks completed successfully."
  environment:
    NODE_ENV: production
    PORT: 3005
    # Add other environment variables as needed
  hooks:
    - echo "Deployment to rauf.trimworldwide.com is complete."
