import "../../public/font/switzer/switzer.css"
import "./globals.css";


export const metadata = {
  title: "Sigi Technologies",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.ico"/>
      </head>
      <body className="font-Switzer">{children}</body>
    </html>
  );
}
